version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'smart-diet-mongo'
    environment: 
      - MONGO_INITDB_DATABASE=smart-diet
      - MONGO_INITDB_USERNAME=root
      - MONGO_INITDB_PASSWORD=secret
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
